name: appemails
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: "^3.7.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.15
  firebase_core: ^3.13.0
  cloud_functions: ^5.5.0
  http: ^0.13.6
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  flutter_launcher_icons: ^0.14.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/ic_launcher_round.png"
    web:
      generate: true
      image_path: "assets/images/ic_launcher_round.png"
flutter:
  uses-material-design: true
