name: appemails
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: "^3.7.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.15
  firebase_core: ^2.10.0
  cloud_functions: ^4.3.0
  http: ^0.13.6
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.17.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
