// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6dVpCwd2REhOmaezRfIhPR8-n5-WLcV4',
    appId: '1:779979423065:web:ae34eaa83f3bc93e18a048',
    messagingSenderId: '779979423065',
    projectId: 'appemails-ef24c',
    authDomain: 'appemails-ef24c.firebaseapp.com',
    storageBucket: 'appemails-ef24c.firebasestorage.app',
    measurementId: 'G-2EQPQE7EJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDikKSfzeqXBp6H8rlIudirJSk-vs23ZfY',
    appId: '1:779979423065:android:2c74530dceb234d318a048',
    messagingSenderId: '779979423065',
    projectId: 'appemails-ef24c',
    storageBucket: 'appemails-ef24c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAObFnwJpcNfFj0fXa0kS_UnPpwX391jvA',
    appId: '1:779979423065:ios:106a0145ba33c81818a048',
    messagingSenderId: '779979423065',
    projectId: 'appemails-ef24c',
    storageBucket: 'appemails-ef24c.firebasestorage.app',
    iosBundleId: 'com.example.appemails',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAObFnwJpcNfFj0fXa0kS_UnPpwX391jvA',
    appId: '1:779979423065:ios:106a0145ba33c81818a048',
    messagingSenderId: '779979423065',
    projectId: 'appemails-ef24c',
    storageBucket: 'appemails-ef24c.firebasestorage.app',
    iosBundleId: 'com.example.appemails',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6dVpCwd2REhOmaezRfIhPR8-n5-WLcV4',
    appId: '1:779979423065:web:19468efc4c2f0d9418a048',
    messagingSenderId: '779979423065',
    projectId: 'appemails-ef24c',
    authDomain: 'appemails-ef24c.firebaseapp.com',
    storageBucket: 'appemails-ef24c.firebasestorage.app',
    measurementId: 'G-NHJ2TQ9003',
  );

}